config/routes.rb
Rails.application.routes.draw do

  resources :vehicle_auto_auctions 

  resources :vehicles

  resources :auctions

  resources :stagings do
    collection { post :import }
  end

  

   root 'vehicle_auto_auctions#index'

end

app/models/auction.rb
class Auction < ActiveRecord::Base
	belongs_to :staging
	has_many :vehicle_auto_auctions
	has_many :vehicles, through: :vehicle_auto_auctions


end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :set_auction, only: [:show, :edit, :update, :destroy]

  # GET /auctions
  # GET /auctions.json
  def index
    @auctions = Auction.all
  end

  # GET /auctions/1
  # GET /auctions/1.json
  def show
  end

  # GET /auctions/new
  def new
    @auction = Auction.new
  end

  # GET /auctions/1/edit
  def edit
  end

  # POST /auctions
  # POST /auctions.json
  def create
    #@auction = Auction.new(auction_params)
    build_location(auction_params)
    respond_to do |format|
      if @auction
        format.html { redirect_to @auction, notice: 'Auction was successfully created.' }
        format.json { render :show, status: :created, location: @auction }
      else
        format.html { render :new }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auctions/1
  # PATCH/PUT /auctions/1.json
  def update
    respond_to do |format|
      if @auction.update(auction_params)
        format.html { redirect_to @auction, notice: 'Auction was successfully updated.' }
        format.json { render :show, status: :ok, location: @auction }
      else
        format.html { render :edit }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1
  # DELETE /auctions/1.json
  def destroy
    @auction.destroy
    respond_to do |format|
      format.html { redirect_to auctions_url, notice: 'Auction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auction
      @auction = Auction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auction_params
      params.require(:auction).permit(:auction_name, :street_address, :city, :state, :zip)
    end
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/_form.html.erb
<%= form_for(@auction) do |f| %>
  <% if @auction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auction.errors.count, "error") %> prohibited this auction from being saved:</h2>

      <ul>
      <% @auction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :auction_name %><br>
    <%= f.text_field :auction_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/auctions/edit.html.erb
<h1>Editing auction</h1>

<%= render 'form' %>

<%= link_to 'Show', @auction %> |
<%= link_to 'Back', auctions_path %>

app/views/auctions/index.html.erb
<h1>Listing auctions</h1>

<table>
  <thead>
    <tr>
      <th>Location name</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auctions.each do |auction| %>
      <tr>
        <td><%= auction.auction_name %></td>
        <td><%= auction.city %></td>
        <td><%= link_to 'Show', auction %></td>
        <td><%= link_to 'Edit', edit_auction_path(auction) %></td>
        <td><%= link_to 'Destroy', auction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Auction', new_auction_path %>

app/views/auctions/new.html.erb
<h1>New auction</h1>

<%= render 'form' %>

<%= link_to 'Back', auctions_path %>

app/views/auctions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location name:</strong>
  <%= @auction.location_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @auction.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @auction.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @auction.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @auction.zip %>
</p>

<%= link_to 'Edit', edit_auction_path(@auction) %> |
<%= link_to 'Back', auctions_path %>