config/routes.rb
Rails.application.routes.draw do

  resources :vehicle_auto_auctions 

  resources :vehicles

  resources :auctions

  resources :stagings do
    collection { post :import }
  end

  

   root 'vehicle_auto_auctions#index'

end

app/models/vehicle_auto_auction.rb
class VehicleAutoAuction < ActiveRecord::Base
	belongs_to :auction
	has_many :vehicles


		def self.total_profit
			array_winning_bids = VehicleAutoAuction.where.not(winning_bid:0).pluck(:winning_bid)
			sum_winning_bids = array_winning_bids.inject{|sum,x| sum + x}
			array_seller_payouts = VehicleAutoAuction.where.not(seller_payout:0).pluck(:seller_payout)
			sum_seller_payouts = array_seller_payouts.inject{|sum,x| sum + x}
			sum_winning_bids - sum_seller_payouts

		end

		def self.number_sold
			array = VehicleAutoAuction.where.not(winning_bid:0).pluck(:winning_bid).count
		end

		def self.average_profit
			array_winning_bids = VehicleAutoAuction.where.not(winning_bid:0).pluck(:winning_bid)
			sum_winning_bids = array_winning_bids.inject{|sum,x| sum + x}
			array_seller_payouts = VehicleAutoAuction.where.not(seller_payout:0).pluck(:seller_payout)
			sum_seller_payouts = array_seller_payouts.inject{|sum,x| sum + x}
			(sum_winning_bids - sum_seller_payouts) / number_sold
		end

		
		
end

app/controllers/vehicle_auto_auctions_controller.rb
class VehicleAutoAuctionsController < ApplicationController
  before_action :set_vehicle_auto_auction, only: [:show, :edit, :update, :destroy]

  # GET /vehicle_auto_auctions
  # GET /vehicle_auto_auctions.json
  def index
    @vehicle_auto_auctions = VehicleAutoAuction.all
  end

  # GET /vehicle_auto_auctions/1
  # GET /vehicle_auto_auctions/1.json
  def show
  end

  # GET /vehicle_auto_auctions/new
  def new
    @vehicle_auto_auction = VehicleAutoAuction.new
  end

  # GET /vehicle_auto_auctions/1/edit
  def edit
  end

  # POST /vehicle_auto_auctions
  # POST /vehicle_auto_auctions.json
  def create
    @vehicle_auto_auction = VehicleAutoAuction.new(vehicle_auto_auction_params)

    respond_to do |format|
      if @vehicle_auto_auction.save
        format.html { redirect_to @vehicle_auto_auction, notice: 'Vehicle auto auction was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle_auto_auction }
      else
        format.html { render :new }
        format.json { render json: @vehicle_auto_auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicle_auto_auctions/1
  # PATCH/PUT /vehicle_auto_auctions/1.json
  def update
    respond_to do |format|
      if @vehicle_auto_auction.update(vehicle_auto_auction_params)
        format.html { redirect_to @vehicle_auto_auction, notice: 'Vehicle auto auction was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle_auto_auction }
      else
        format.html { render :edit }
        format.json { render json: @vehicle_auto_auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicle_auto_auctions/1
  # DELETE /vehicle_auto_auctions/1.json
  def destroy
    @vehicle_auto_auction.destroy
    respond_to do |format|
      format.html { redirect_to vehicle_auto_auctions_url, notice: 'Vehicle auto auction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle_auto_auction
      @vehicle_auto_auction = VehicleAutoAuction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_auto_auction_params
      params.require(:vehicle_auto_auction).permit(:auction_id, :vehicle_id, :winning_bid, :seller_payout, :description)
    end
end

app/helpers/vehicle_auto_auctions_helper.rb
module VehicleAutoAuctionsHelper
end

app/views/vehicle_auto_auctions/_form.html.erb
<%= form_for(@vehicle_auto_auction) do |f| %>
  <% if @vehicle_auto_auction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle_auto_auction.errors.count, "error") %> prohibited this vehicle_auto_auction from being saved:</h2>

      <ul>
      <% @vehicle_auto_auction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :auction_id %><br>
    <%= f.number_field :auction_id %>
  </div>
  <div class="field">
    <%= f.label :vehicle_id %><br>
    <%= f.number_field :vehicle_id %>
  </div>
  <div class="field">
    <%= f.label :winning_bid %><br>
    <%= f.number_field :winning_bid %>
  </div>
  <div class="field">
    <%= f.label :seller_payout %><br>
    <%= f.number_field :seller_payout %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicle_auto_auctions/edit.html.erb
<h1>Editing vehicle_auto_auction</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle_auto_auction %> |
<%= link_to 'Back', vehicle_auto_auctions_path %>

app/views/vehicle_auto_auctions/index.html.erb
<h1>Listing vehicle_auto_auctions</h1>

<table>
  <thead>
    <tr>
      <th>Auction Id</th>
      <th>Auction Name</th>
      <th>Vehicle</th>
      <th>Winning bid</th>
      <th>Seller payout</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicle_auto_auctions.each do |vehicle_auto_auction| %>
      <tr>
        <td><%= vehicle_auto_auction.auction_id %></td>
        <td><%= vehicle_auto_auction.auction_name %></td>
        <td><%= vehicle_auto_auction.vehicle_id %></td>
        <td><%= vehicle_auto_auction.winning_bid %></td>
        <td><%= vehicle_auto_auction.seller_payout %></td>
        <td><%= vehicle_auto_auction.description %></td>
         
        <td><%= link_to 'Show', vehicle_auto_auction %></td>
        <td><%= link_to 'Edit', edit_vehicle_auto_auction_path(vehicle_auto_auction) %></td>
        <td><%= link_to 'Destroy', vehicle_auto_auction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

    <p>"Total Auction Profit: $<%= @vehicle_auto_auctions.total_profit  %>.00"</p>
    <p>"Average Auction Profit: $<%= @vehicle_auto_auctions.average_profit  %>.00"</p>
    <p>"Total Vehicles Sold: <%= @vehicle_auto_auctions.number_sold  %>"</p>

  </tbody>
</table>

<br>

<h2>Importing File</h2>
<%= form_tag import_stagings_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
<%= link_to 'New Vehicle auto auction', new_vehicle_auto_auction_path %>

app/views/vehicle_auto_auctions/new.html.erb
<h1>New vehicle_auto_auction</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicle_auto_auctions_path %>

app/views/vehicle_auto_auctions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Auction:</strong>
  <%= @vehicle_auto_auction.auction_id %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @vehicle_auto_auction.vehicle_id %>
</p>

<p>
  <strong>Winning bid:</strong>
  <%= @vehicle_auto_auction.winning_bid %>
</p>

<p>
  <strong>Seller payout:</strong>
  <%= @vehicle_auto_auction.seller_payout %>
</p>

<p>
  <strong>Description:</strong>
  <%= @vehicle_auto_auction.description %>
</p>

<%= link_to 'Edit', edit_vehicle_auto_auction_path(@vehicle_auto_auction) %> |
<%= link_to 'Back', vehicle_auto_auctions_path %>